usersignup:
  path: /user/create
  controller: App\Controller\UserController::create
  methods: [POST, OPTIONS]
  defaults:
    _format: json

users:
  path: /users
  controller: App\Controller\UserController::list
  methods: [GET, HEAD]
  defaults:
    _format: json

user:
  path: /user/{id}
  controller: App\Controller\UserController::index
  methods: [GET, HEAD]
  defaults:
    _format: json

apartments:
  path: /apartments
  controller: App\Controller\ApartmentController::list
  methods: [GET, HEAD]

apartment:
  path: /apartment/{id}
  controller: App\Controller\ApartmentController::index
  methods: [GET, HEAD]
  defaults:
    _format: json
  requirements:
    page: '\d+'

apartment_edit:
  path: /apartment/{id}
  controller: App\Controller\ApartmentController::index
  methods: [GET, PUT, OPTIONS]
  requirements:
    page: '\d+'
  defaults:
    _format: json

apartment_create:
  path: /apartments/create
  controller: App\Controller\ApartmentController::create
  methods: [POST, OPTIONS]
  # defaults:
  #   _format: json